checks:
    php:
        use_self_instead_of_fqcn: true
        uppercase_constants: true
        return_doc_comments: true
        simplify_boolean_return: true
        return_doc_comment_if_not_inferrable: true
        properties_in_camelcaps: true
        parameters_in_camelcaps: true
        overriding_parameter: true
        check_method_contracts:
            verify_interface_like_constraints: true
            verify_documented_constraints: true
            verify_parent_constraints: true
        avoid_todo_comments: true
        encourage_single_quotes: true
        line_length:
            max_length: '120'
        function_in_camel_caps: true
        excluded_dependencies:
            - myclabs/deep-copy
            - symfony/symfony

filter: {  }
coding_style:
    php: {  }
build:
    environment:
        php:
            version: 5.6.9
            version: 7.0.0
